# Generated by Django 4.2.6 on 2023-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translate', models.CharField(max_length=255)),
                ('defenition', models.CharField(max_length=255)),
            ],
        ),
    ]
